#!/usr/bin/env bash
# Does synthetic data holding deliberate CONFUSABLE material pairs lift real IoU?
#
# The 2026-08-10 handoff named this the untried lever, on the premise that
# `generate_synthetic_v5.py` picks distinct tiles per family "by construction, so
# synthetic sheets contain no confusable pairs at all". Measurement says the
# premise is wrong -- it picks distinct file PATHS, and ~19% of multi-family
# synthetic images already carry a pair at >=0.90 similarity against ~24% of real
# ones (scripts/family_similarity_probe.py). This tests the lever anyway, at a
# maximum dose: --confusable-prob 1.0 takes the rate to ~75%.
#
# Both arms are generated by the SAME generator at the SAME seed with the SAME
# mode weights, so the only difference is the flag. Compare the arms to each
# other, NOT to the 0.6860 headline -- the headline's synthetic half comes from
# the HF 20k parquet, an older generator recipe.
#
# Screening budget: run-to-run sd on mix3652 is 0.0262, so single-seed gaps under
# ~0.05 mean nothing. Three seeds, epochs chosen on validation, never on HF14.
set -euo pipefail
cd /home/ubuntu/lambda-patterns-instance
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export MPLCONFIGDIR=/tmp/matplotlib
COMMON="--batch-size 8 --num-workers 24 --prefetch-factor 4 \
  --image-max-size 1280 --ref-size 224 --width 128 \
  --lr 2e-4 --backbone-lr-mult 0.1 --train-split 0.99 \
  --domain-random --mask-thresh 0.35"

for SEED in 31 7 99; do
  for ARM in confbase confpair; do
    CK=data/runs/ck_${ARM}_mix3652_s${SEED}
    DATA=data/mixed/${ARM}1600_rf1548_gen504
    [ -f "$CK/epoch_8.pth" ] && { echo "skip $CK"; continue; }
    echo "=== $ARM seed $SEED ==="
    PYTHONPATH=. python3 scripts/train_refunet.py --local-data "$DATA" \
      --checkpoint-dir "$CK" --epochs 1 --schedule-epochs 10 --seed "$SEED" $COMMON \
      > "logs_${ARM}_s${SEED}_A.log" 2>&1
    PYTHONPATH=. python3 scripts/train_refunet.py --local-data "$DATA" \
      --checkpoint-dir "$CK" --epochs 8 --schedule-epochs 9 --seed "$SEED" $COMMON \
      --reset-optimizer --init-from "$CK/epoch_0.pth" \
      > "logs_${ARM}_s${SEED}_B.log" 2>&1
  done
done
echo CONFUSABLE_ABLATION_DONE
